---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/zfs.openebs.io/zfsvolume_v1.json
apiVersion: zfs.openebs.io/v1
kind: ZFSVolume
metadata:
  name: paperless
  finalizers:
    - cluster.local/data-protection
spec:
  capacity: "10737418240"
  fsType: zfs
  ownerNodeID: m00nsrv
  poolName: vault
  shared: "yes"
  encryption: "on"
  keylocation: file:///root/paperless.key
  keyformat: raw
  compression: on
  dedup: on
  thinProvision: "yes"
  volumeType: DATASET
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-zfs-paperless
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/cas-type: localpv-zfs
      openebs.io/poolname: vault
    volumeHandle: paperless
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: openebs.io/nodeid
              operator: In
              values:
                - m00nsrv
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
