---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/zfs.openebs.io/zfsvolume_v1.json
apiVersion: zfs.openebs.io/v1
kind: ZFSVolume
metadata:
  name: photos
  finalizers:
    - cluster.local/data-protection
spec:
  capacity: "64424509440"
  compression: "lz4"
  dedup: "off"
  fsType: zfs
  ownerNodeID: m00nsrv
  poolName: vault/storage
  recordsize: 1M
  shared: "yes"
  thinProvision: "yes"
  volumeType: DATASET
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-zfs-photos
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 60Gi
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/cas-type: localpv-zfs
      openebs.io/poolname: vault/storage
    volumeHandle: photos
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: openebs.io/nodeid
              operator: In
              values:
                - m00nsrv
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
