---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app ${APP}
spec:
  secretStoreRef:
    kind: SecretStore
    name: k8s-store-default-ns
  target:
    name: "${APP}-config"
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: "vikunja-configmap"
            items:
              - key: config.yaml
  data:
    - secretKey: client_secret
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: k8s-store-default-ns
      remoteRef:
        key: kanidm-${APP}-oidc
        property: client-secret
