apiVersion: v1
kind: Secret
metadata:
  name: vikunja
stringData:
  VIKUNJA_SERVICE_JWT_SECRET: ENC[AES256_GCM,data:aF1l7ASh7q8zyQtrhIeb1zlfSEBYgsyW5925ffbFGHtsvLORRaI8MuPVIQi+M1MxDT7sJhRwMLCzLtRF38VB9hSqZkU/HynMR4Bd0qJZmuAlfa0PCUeLBA==,iv:6WybA2sTdTHNN47jTfLnnPLETn1aiZ8dPTohIR1dodk=,tag:wnqtY3MQ+pwBBag3CDs4jg==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMFZxc0VmQkV2VTRqRzBC
        ZEJ1ZXFSZnJhT1V4TlpNbThlSjgvUVVkUG5rCk1wN2YrTGRscGx3VmJIeDE5bE9O
        ZTFXVGFPNWliQW42Q1YzS010OXlDWVUKLS0tIFZOVW8valF3Qk1leEF2Tk9zODRM
        SCtFeWJ0bHFFckczaklHUVJpSVpWQzAKAUI6+DE3TugGIRnGo8qCt8wl4ubGotc7
        cqlAFMJjIyHkOufNZbq7Bq2/Ex4nwq0wq5f8FbAQB9O+sB71stuIew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T17:22:16Z"
  mac: ENC[AES256_GCM,data:lPKFVJr9vxK53AwBxso3KdeDSmsJ82LdkOqj1AnFSOlixIa3jSUiyQnK0nNwoI5Adx0/bZ74BuPuur8IEVFbvB8g5UOU7C50PfJl6XmVj7lE3oz/Y+XClQ1LzCV/PLN8aIerwRewuibLeFLc7X7QB3RKzq7PlDM1TeNyUZ0yXo0=,iv:U+17edWXv3/jmNEr8sIDVyio4idAk35GFlt3mGKyKDk=,tag:EdJeV4ZtGVpbwvo+Y3B0EQ==,type:str]
  pgp:
    - created_at: "2025-06-19T02:12:25Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdA/K0f5jrjrvPEk+D73ZbU+juAPhUC0moI8jsBkKL7gDow
        JeFcZJU/oQBa4IKMPbViXnZ4lphIpH38zrnGiZceCivu/iIatO8qytT0S44/j7H/
        0l4BuD04Jg+4d0Kv15lcAMeZaB1LCDLXqnVzap3nzNFHSHZv8IhKb6g6MWEkUr/y
        htdlMndiSLw816xZMy8+F5y5fRdaze3LLd6N7ryDC65w1wQA/TQFnpMcliRVSxgY
        =nW+9
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
