---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app renovate-operator
  namespace: &namespace renovate
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
   - ../../../../components/oidc/envoy
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/renovate/renovate-operator/app
  prune: true
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      OIDC_DISPLAY_NAME: Renovate
      OIDC_GROUP: admins
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-config
  namespace: &namespace renovate
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate-operator
  components: []
  dependsOn:
    - name: renovate-operator
      namespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/renovate/renovate-operator/config
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
