---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plugin-barman-cloud
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.1
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
---
# yaml-language-server: $schema=https://flux.tholinka.dev/helmrelease/v2/github/cloudnative-pg/charts/main/charts/plugin-barman-cloud
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plugin-barman-cloud
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
