---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/common
resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./gateway-api/ks.yaml
  - ./generic-cdi-plugin/ks.yaml
  - ./generic-device-plugin/ks.yaml
  - ./ksgate/ks.yaml
  - ./kube/ks.yaml
  - ./metrics-server/ks.yaml
  # - ./nvidia-device-plugin/ks.yaml
  - ./reloader/ks.yaml
  - ./reflector/ks.yaml
  - ./sealed-secrets/ks.yaml
  - ./snapshot-controller/ks.yaml
#  - ./spegel/ks.yaml
