---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-apiserver
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/oidc
  interval: 1h
  path: ./kubernetes/apps/default/kube/apiserver
  postBuild:
    substitute:
      APP: kubernetes
      NAMESPACE: *namespace
      OIDC_PUBLIC_CLIENT: "true"
      DOMAIN: http://localhost:8000
      OIDC_DISPLAY_NAME: "Kubernetes"
      OIDC_CALLBACK: /
      OIDC_EXTRA_CALLBACKS: '["http://localhost:18000/"]'
      OIDC_GROUP: k8s_admins
      OIDC_SCOPES: '["openid", "groups", "email", "offline_access"]'
      OIDC_CUSTOM_STATE: |
        {
          "groups": {
            "k8s_admins": {
              "members": ["idm_admins", "admins"]
            }
          }
        }
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
