---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-lan
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-lan",
      "plugins": [
        {
          "type": "macvlan",
          "master": "lan0",
          "mode": "bridge",
          "ipam": {
            "type": "host-local",
            "ranges": [
              [
                {
                  "subnet": "192.168.0.0/24",
                  "rangeStart": "192.168.0.100",
                  "rangeEnd": "192.168.0.199",
                  "gateway": "192.168.0.1"
                }
              ],
              [
                {
                  "subnet": "fd42:78a5:2c09::/64",
                  "rangeStart": "fd42:78a5:2c09::100",
                  "rangeEnd": "fd42:78a5:2c09::1ff",
                  "gateway": "fd42:78a5:2c09::1"
                }
              ]
            ]
          }
        },
        {
          "type": "sbr"
        }
      ]
    }
