---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "photos-volsync-mega"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-store-volsync-ns
  target:
    name: "photos-volsync-mega-secret"
    template:
      data:
        RESTIC_REPOSITORY: "rclone:mega:backups/photos"
        #        RESTIC_REPOSITORY: "rest:http://rclone-server.volsync-system.svc.cluster.local/photos/"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: volsync-mega-template
