---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "photos-mega"
spec:
  sourcePVC: "photos"
  trigger:
    schedule: "30 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: "photos-volsync-mega-secret"
    volumeSnapshotClassName: "csi-zfs"
    cacheCapacity: "5Gi"
    cacheStorageClassName: "zfs-spark"
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: "zfs-vault"
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    retain:
      daily: 7
