---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app heisenbridge
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      *app :
        containers:
          app:
            image:
              repository: docker.io/hif1/heisenbridge
              tag: 1.15.4@sha256:4648b0987d37ea9f398e93940bafb32b4f0fa0ff1a7611af993a35ea4debc03f
              pullPolicy: IfNotPresent
            args:
              [
                "-c=/etc/config.yaml",
                "-l=::",
                "-p=9898",
                "http://continuwuity.matrix.svc",
                "-vv",
              ]
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 100Mi

    service:
      app:
        controller: *app
        # clusterIP: None
        ports:
          http:
            port: 80
            targetPort: 9898

    route:
      app:
        hostnames: ["matrix.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - matches:
              - path:
                  value: /_heisenbridge/media/

    persistence:
      config:
        type: secret
        name: heisenbridge-config
        globalMounts:
          - path: /etc/config.yaml
            subPath: registration.yaml
