---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: opencloud-configmap
    files:
      - ./resources/csp.yaml
      - ./resources/proxy.yaml
secretGenerator:
  - name: opencloud-secret
    files:
      - opencloud.yaml=./resources/opencloud.sops.yaml
configurations:
  - resources/kustomizeconfig.yaml
