---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app autobrr
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/oidc
    - ../../../../components/database
    - ../../../../components/gatus/guarded
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/media/autobrr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      OIDC_CALLBACK: /api/auth/oidc/callback
      OIDC_GROUP: admins
      OIDC_SHORT_USERNAME: "true"
      OIDC_LEGACY_CRYPTO: "true"
      OIDC_DISABLE_PKCE: "true"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
