---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
spec:
  interval: 1h
  url: https://bitnami-labs.github.io/sealed-secrets
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  interval: 1h
  chart:
    spec:
      chart: sealed-secrets
      version: v2.17.2
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: kube-system
  values:
    fullnameOverride: sealed-secrets-controller
