---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-login
spec:
  provider:
    webhook:
      url: http://bitwarden:8087/object/item/{{ .remoteRef.key }}
      headers:
        Content-Type: application/json
      result:
        jsonPath: $.data.login.{{ .remoteRef.property }}
