# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: &name bitwarden
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: *name
      app.kubernetes.io/name: *name
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: external-secrets
            app.kubernetes.io/name: external-secrets
            k8s:io.kubernetes.pod.namespace: external-secrets
      toPorts:
        - ports:
            - port: "8087"
              protocol: TCP
  egress:
    - toPorts:
        - ports:
            - port: "10443"
              protocol: TCP
    - toFQDNs:
        - matchName: api.bitwarden.com
        - matchName: vaultwarden.m00nlit.dev
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: coredns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
#    - toEndpoints:
#        - matchLabels:
#            app.kubernetes.io/instance: vaultwarden
#            app.kubernetes.io/name: vaultwarden
#            io.kubernetes.pod.namespace: default
