---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/generators.external-secrets.io/clustergenerator_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: pw
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 64
      noUpper: false
      allowRepeat: true
