---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/bitnami.com/sealedsecret_v1alpha1.json
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng
  namespace: default
spec:
  encryptedData:
    SEARXNG_SECRET: AgAcZaBBBF78i3Ai16uMW4eta7HF0dIhx712rkBAlnxPRTy5A2mrCCR99eYjKo728+kdoe66P+f8hvn9cXxZNHgIjTME8BWphDX/i1NtOImkcwMz4nV24UHHqN4SqVRuD1zOx2LLTsa4a9QQeEEfj3l4M/u0t4eqeJ54Hsq5dQPECFLiyWtUkKK/aTPZS0nlaYofnVfOmkFVBZVLETYPG0zIc3gJNAZK9MUtW0bGQ5l2vl1cnnRuX7mFXDxJKG30klTa3z2uw2/EKZxOejuibMnxmF0dAg3L27Ri+6kgjxhr96BL85oRN2ylz+1sma+twnOPVrImU+LFEG7eM6sPrSAxuc3mpVXda9LOmYakLj+IkKPYM9jIO5hyrp09uJgYaGeiS9On0lQg+Jn3mVlKAmHtQ14yUmpFklVuOjTyKm9bV63Bi4h3vkyJLRIPU24K7LMY9UYARmvVAj/odsOwybELnlE/jC6p5GeqIyFC09vx7D83vhzmGmN9xHmJDDw1KzR9ddZfcOAdclAnjKqPVs7hRE7g+zNJz6u7bTqhC/9C4zUdNpm4ChbIoWCj21qTkHskthkpwbD/4u3rD6N14UvH7hDmhkpd3bwza4xpz9qKOfYWAVhDoK0qCDavZ4x1YDvtzVI8b8B1LCU9xmhhDp9dehqddeham6tc0MEk2K6Vz1SHyrmIrt5FMua9bVl7jjQ=
