---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/envoyproxy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: internal
spec:
  ipFamily: DualStack
  backendTLS:
    ecdhCurves:
      - X25519
      - P-256
      - P-384
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        container:
          image: mirror.gcr.io/envoyproxy/envoy:v1.37.0@sha256:d9b4a70739d92b3e28cd407f106b0e90d55df453d7d87773efd22b4429777fe8
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
  #  shutdown:
  #    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Gzip
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/envoyproxy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: external
spec:
  ipFamily: IPv6
  backendTLS:
    ecdhCurves:
      - X25519
      - P-256
      - P-384
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        container:
          image: mirror.gcr.io/envoyproxy/envoy:v1.37.0@sha256:d9b4a70739d92b3e28cd407f106b0e90d55df453d7d87773efd22b4429777fe8
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        loadBalancerClass: "io.cilium/node"
  #  shutdown:
  #    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Gzip
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/envoyproxy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: cftunnel
spec:
  ipFamily: IPv6
  backendTLS:
    ecdhCurves:
      - X25519
      - P-256
      - P-384
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 1
        container:
          image: mirror.gcr.io/envoyproxy/envoy:v1.37.0@sha256:d9b4a70739d92b3e28cd407f106b0e90d55df453d7d87773efd22b4429777fe8
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        type: ClusterIP
  #  shutdown:
  #    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Gzip
