---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/tailscale.com/connector_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-lbs
  annotations:
    tailscale.com/proxy-group: ingress-proxy
spec:
  hostname: ts-lbs
  subnetRouter:
    advertiseRoutes:
      - "fd42:78a5:2c09::200/120"
      - "192.168.0.192/26"
