---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/tailscale.com/proxygroup_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ingress-proxy
spec:
  type: ingress
  replicas: 2
