---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app openclaw
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components: []
  dependsOn:
    - name: kubevirt
      namespace: kubevirt
  interval: 1h
  path: "./kubernetes/apps/openclaw/openclaw/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: openclaw
  timeout: 5m
