---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rustical
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/oidc
    - ../../../../components/volsync
    - ../../../../components/gatus/guarded
  dependsOn:
    - name: volsync
      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/default/rustical/app
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      VOLSYNC_CAPACITY: 1Gi
      OIDC_DISPLAY_NAME: RustiCal
      OIDC_CALLBACK: /frontend/login/oidc/callback
      OIDC_SHORT_USERNAME: "true"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
