---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dragonfly-${APP}-cert
spec:
  secretName: dragonfly-${APP}-cert
  usages:
    - client auth
  commonName: ${REDIS_OWNER:=${APP}}
  issuerRef:
    name: dragonfly-client-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
