---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app freshrss
  namespace: &namespace default
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/oidc
    - ../../../../components/volsync
    - ../../../../components/database
    - ../../../../components/gatus/guarded
  dependsOn:
    - name: volsync
      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/default/freshrss/app
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      VOLSYNC_PUID: "33"
      VOLSYNC_PGID: "33"
      GATUS_STATUS: "401"
      OIDC_DISPLAY_NAME: "FreshRSS"
      OIDC_CALLBACK: /i/oidc/
      OIDC_SHORT_USERNAME: "true"
      OIDC_DISABLE_PKCE: "true"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
