# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: host-firewall-basic
spec:
  nodeSelector:
    matchLabels: {}
  ingress:
    - toPorts:
        - ports:
            - port: "22" # SSH
              protocol: TCP
            - port: "41641" # Tailscale
              protocol: UDP
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: control-plane
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/control-plane: "true"
  ingress:
    # Operators
    - fromEntities:
        - remote-node
        - host
      toPorts:
        - ports:
            - port: "6443" # kube-apiserver
              protocol: TCP

    # API Access from Tailscale
    - fromCIDR:
        - fd7a:115c:a1e0::/48
        - 100.64.0.0/10
      toPorts:
        - ports:
            - port: "6443" # kube-apiserver
              protocol: TCP
            # - port: "9090" # Cockpit
            #   protocol: TCP

    # etcd peer -> etcd peer
    - fromNodes:
        - matchLabels:
            node-role.kubernetes.io/control-plane: "true"
      toPorts:
        - ports:
            - port: "2380"
              protocol: TCP
#  egress:
#    # etcd peer -> etcd peer
#    - toNodes:
#        - matchLabels:
#            node-role.kubernetes.io/control-plane: "true"
#      toPorts:
#        - ports:
#            - port: '2380'
#              protocol: TCP
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: kubelet
spec:
  nodeSelector:
    # apply to all nodes
    matchLabels: {}
  ingress:
    # api server -> kubelet
    - fromEntities:
        # - kube-apiserver
        - cluster
    - toPorts:
        - ports:
            - port: "10250"
              protocol: TCP
#  egress:
#    # kubelet -> load balancer
#    - toEntities:
#        - kube-apiserver
#      toPorts:
#        - ports:
#            - port: '6443'
#              protocol: TCP
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: cilium-health
specs:
  - endpointSelector:
      # apply to health endpoints
      matchLabels:
        reserved:health: ""
    ingress:
      # cilium agent -> cilium agent
      - fromEntities:
          - host
          - remote-node
        toPorts:
          - ports:
              - port: "4240"
                protocol: TCP
  - nodeSelector:
      # apply to all nodes
      matchLabels: {}
    ingress:
      # cilium agent -> cilium agent
      - fromEntities:
          - health
          - remote-node
        toPorts:
          - ports:
              - port: "4240"
                protocol: TCP
#    egress:
#      # cilium agent -> cilium agent
#      - toEntities:
#          - health
#          - remote-node
#        toPorts:
#          - ports:
#              - port: '4240'
#                protocol: TCP
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: prometheus-metrics
spec:
  nodeSelector:
    # apply to all nodes
    matchLabels: {}
  ingress:
    # prometheus -> node exporter
    - fromEndpoints:
        - matchLabels:
            prometheus: prometheus-kube-prometheus-prometheus
      toPorts:
        - ports:
            - port: "9100"
              protocol: TCP
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: host-firewall-ingress
spec:
  nodeSelector:
    matchLabels: {}
  ingress:
    - toPorts:
        - ports:
            - port: "443" # HTTPS
              protocol: TCP
            - port: "443" # HTTP3
              protocol: UDP
            - port: "80" # HTTP
              protocol: TCP
            - port: "53" # DNS
              protocol: TCP
            - port: "53" # DNS
              protocol: UDP
