---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-ca
spec:
  isCA: true
  commonName: hubble-ca
  subject:
    countries:
      - PL
    organizations:
      - homelab-cluster
  usages:
    - cert sign
    - crl sign
  nameConstraints:
    critical: true
    permitted:
      dnsDomains: &domains
        - .cilium.io
        - .hubble-relay.cilium.io
        - .default.hubble-grpc.cilium.io
      uriDomains: *domains
  duration: 87660h # 10 years
  privateKey:
    algorithm: Ed25519
    encoding: PKCS8
    rotationPolicy: Never
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: hubble-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: hubble-ca
spec:
  ca:
    secretName: hubble-ca
