---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  allowFirstLastIPs: No
  blocks:
    - cidr: "192.168.0.200/29"
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  loadBalancerIPs: true
  interfaces:
    - lan0
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
