---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-webui
  namespace: &namespace ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/oidc
    - ../../../../components/volsync
    - ../../../../components/database
    - ../../../../components/gatus/guarded
  dependsOn:
    - name: volsync
      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/ai/open-webui/app
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      OIDC_DISPLAY_NAME: "Open WebUI"
      OIDC_CALLBACK: /oauth/oidc/callback
      OIDC_CLAIM_MAPS: |
        {
          "roles": {
            "joinType": "array",
            "valuesByGroup": {
              "users@idm.m00nlit.dev": ["user"],
              "admins@idm.m00nlit.dev": ["admin"]
            }
          }
        }
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
