---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: voltkonekt-wordpresss
spec:
  hostnames:
    - "voltkonekt.pl"
  parentRefs:
    - name: cftunnel
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: wordpress
          namespace: default
          port: 80
