---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
# openapi:
#   path: http://crd-patcher.default.svc/definitions.json?crd=helm.toolkit.fluxcd.io.v2.HelmRelease&extraProp=helm.toolkit.fluxcd.io.v2.HelmRelease:spec.values.defaultPodOptions.schedulingGates
patches:
  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: not-used
      spec:
        values:
          defaultPodOptions:
            annotations:
              k8s.ksgate.org/postgres-ready: |
                {
                  "apiVersion": "postgresql.cnpg.io/v1",
                  "kind": "Cluster",
                  "name": "postgres",
                  "namespace": "postgres",
                  "expression": "resource.status.readyInstances >= 1"
                }
              k8s.ksgate.org/postgres-service: |
                {
                  "apiVersion": "v1",
                  "kind": "Service",
                  "name": "postgres-rw",
                  "namespace": "postgres"
                }
              k8s.ksgate.org/database-applied: |
                {
                  "apiVersion": "postgresql.cnpg.io/v1",
                  "kind": "Database",
                  "name": "postgres-${APP}",
                  "namespace": "postgres",
                  "expression": "resource.status.applied"
                }
            schedulingGates:
              - name: k8s.ksgate.org/postgres-ready
              - name: k8s.ksgate.org/postgres-service
              - name: k8s.ksgate.org/database-applied
          persistence:
            postgres-certs:
              type: secret
              name: "postgres-{{ .Release.Name }}-cert"
              defaultMode: 0440
              globalMounts:
                - path: /var/run/secrets/postgresql
            root-ca:
              type: secret
              name: "root-ca"
              defaultMode: 0440
              globalMounts:
                - path: /var/run/secrets/root-ca
