---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
configMapGenerator:
  - name: qbittorrent-coredns-configmap
    files:
      - ./resources/Corefile
# secretGenerator:
#   - name: gluetun-secret
#     files:
#       - auth.toml=./resources/auth.sops.toml
configurations:
  - ./resources/kustomizeconfig.yaml
generatorOptions:
  disableNameSuffixHash: true
