---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-forgejo
spec:
  discoveryFilter: m00n/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_PLATFORM
      value: forgejo
    - name: RENOVATE_ENDPOINT
      value: https://git.${SECRET_DOMAIN}/api/v1
    - name: RENOVATE_GIT_AUTHOR
      value: "Renovate <renovate@${SECRET_DOMAIN}>"
    - name: RENOVATE_ONBOARDING_CONFIG
      value: |
        {
          "$schema": "https://docs.renovatebot.com/renovate-schema.json",
          "extends": [
            'config:recommended'
          ]
        }
    - name: RENOVATE_ALLOW_PLUGINS
      value: "true"
  image: ghcr.io/renovatebot/renovate:42.76.3@sha256:64dad0bc6f6be5504a05580bb609a619159204c8f88f049edfb0531c1fba60e8
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: "@hourly"
  secretRef: renovate-secret
  webhook:
    enabled: true
