---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/bitnami.com/sealedsecret_v1alpha1.json
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-secret
  namespace: media
spec:
  encryptedData:
    api_key: AgCPMliAVoz5Iy2gR8bjYTtdUcQhNMQWc63bAZOeTF3YHR7holi55/7CM3+I/xYpUSvtqmbDo2HhD3mxC+eIQ+m3wmcXC/k18zSv7q5mLBQyjtQp9yoy0TqfWl5KGsCp1EmBuSVUvotFUtz8V2yG6TMsgeZbf2MsY+EeYBSFDE6dnM6ZaGQTC9Kl0RaiX5Nflzkmnva0Fumu25of64kFaEJ71CdycbazsYi08/E4N3VrYSMMo7zDRwQJ9P8VGUxy8ZgH4CtTKnMVX1uo+7KNsI+nxcXykfioc2k3WtHrQzX93FfWDEZyEAW5i8NKjLsexdpAT2J78BfYm+AvJQ7Gf7ZuBFZ8ZXyYJlRcFCydUv96yUdhNkmgBxvCYIbLly9egfwrECCGl59fwWBLrA5vITpVuId2zaYUDNw1yDt1nAz3wuKi0/fh5kBdNGjpgoic7cLMjw4kXm+9+wo/6vPNngX3V6vR2Kjfx4D4jBwjedqQEr33C7idk27ot4l8qw7VL8W6PM25Zlb/Q1AdSqaXxtYsMp0K4WNnwZnJeyIrtIF+LE4LfdCv86GNvnz7dvC8VwGmSkZGIWc61uxQP5zeQ4FQvt3h23vNxtczgw9uh4pihMGFKlwRFHAZVaodV10C4WWVl1LD+e5hBVgPLFSLXWDcyoEiiVyIY6DqccL/qeVTL7ol/DL5Mbphmk6i49zWJHfAvvXURoqE3MgiSTXE7e1DHpYL65cQC69lX+pt9MdSEg==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "homepage"
