---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rssflow
  namespace: &namespace rssflow
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/database
    - ../../../../components/dragonfly
  interval: 1h
  path: ./kubernetes/apps/rssflow/rssflow/app
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rssflow-websub-db
  namespace: &namespace postgres
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app rssflow-websub
  components: []
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
  interval: 1h
  path: ./kubernetes/components/database/base/postgres
  postBuild:
    substitute:
      APP: *app
      OWNER: rssflow
  healthChecks:
    - name: postgres-rssflow-websub
      namespace: *namespace
      kind: Database
      apiVersion: postgresql.cnpg.io/v1
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
