# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: publish-k8s-schemas-secret
stringData:
    CLOUDFLARE_ACCOUNT_ID: adsa
    CLOUDFLARE_API_TOKEN: sdad
