---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app publish-k8s-schemas
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components: []
  interval: 1h
  path: "./kubernetes/apps/default/publish-k8s-schemas/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
  wait: false
