---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/trust.cert-manager.io/bundle_v1alpha1.json
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: root-ca
spec:
  sources:
    - secret:
        name: "cluster-ca-cert"
        key: "tls.crt"
  target:
    configMap:
      key: "ca.crt"
    secret:
      key: "ca.crt"
# ---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/trust.cert-manager.io/bundle_v1alpha1.json
# apiVersion: trust.cert-manager.io/v1alpha1
# kind: Bundle
# metadata:
#   name: postgres-client-ca
# spec:
#   sources:
#     - secret:
#         name: postgres-client-ca
#         key: "tls.crt"
#   target:
#     secret:
#       key: "ca.crt"
#       metadata:
#         labels:
#           cnpg.io/reload: ""
