---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kaniop
  namespace: &namespace kanidm
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components: []
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/kanidm/kanidm/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kanidm
  namespace: &namespace kanidm
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
    - ../../../../components/gatus/external
    - ../../../../components/tls
  dependsOn:
    # - name: kaniop
    #   namespace: kanidm
    - name: volsync
      namespace: volsync-system
  #  healthChecks:
  #    - apiVersion: helm.toolkit.fluxcd.io/v2
  #      kind: HelmRelease
  #      name: *app
  #      namespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/kanidm/kanidm/instance
  postBuild:
    substitute:
      APP: *app
      SUBDOMAIN: idm
      TLS_KEY_SIZE: "256"
      VOLSYNC_PUID: "999"
      VOLSYNC_PGID: "999"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
