---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mautrix-meta
  namespace: &namespace matrix
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    #    - ../../../../components/volsync
    - ../../../../components/database
  #  dependsOn:
  #    - name: volsync
  #      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/matrix/mautrix-meta/app
  postBuild:
    substitute:
      APP: *app
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
