system:
  configured_version: 0.10.1
  timezone: ${TZ}
  card_enabled: true
  cal_enabled: true
  dav_auth_type: Basic
  admin_passwordhash: "{{ .admin_passwordhash }}"
  failed_access_message: "user %u authentication failure for Baikal"
  auth_realm: BaikalDAV
  base_uri: ""
  invite_from: ""
database:
  sqlite_file: ""
  backend: pgsql
  mysql_host: ""
  mysql_dbname: ""
  mysql_username: ""
  mysql_password: ""
  encryption_key: "{{ .encryption_key }}"
  pgsql_host: "pooler-rw.postgres.svc"
  pgsql_dbname: "baikal"
  pgsql_username: "baikal"
  pgsql_password: "baikal"
