---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./anubis/ks.yaml
  - ./attic/ks.yaml
  - ./atuin/ks.yaml
  - ./baikal/ks.yaml
  - ./crd-patcher/ks.yaml
  - ./dawarich/ks.yaml
  #  - ./firefly/ks.yaml
  - ./freshrss/ks.yaml
  - ./karakeep/ks.yaml
  - ./krr/ks.yaml
  - ./kube/ks.yaml
  - ./mealie/ks.yaml
  - ./ntfy/ks.yaml
  - ./paperless/ks.yaml
  - ./publish-k8s-schemas/ks.yaml
  - ./rustical/ks.yaml
  - ./searxng/ks.yaml
  - ./tika/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./vikunja/ks.yaml
  - ./wks/ks.yaml
  - ./wordpress/ks.yaml
