---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: prowlarr-secret
    namespace: media
spec:
    encryptedData:
        api_key: AgDJD9Zgj/SxmkeS/jSTLkJD5H7ly1NYU1d8sKDXPAzk2s7xZwSJRlRqroPIVS2KE/ClAxACPsj5XwO9yAVz57drbqTFQ3bYNYeRruI76wSlQ7Ky9SABUV9LrD5KsduyHszVVkcRyztYoW8yEnV4qnGxWpX6brQQVRuAQYPrp4ChgRi4UFdHSA7dOtxWsOyIdlaMOEm9prY2vMr9J0OCq/XFOZBSSNwzHQqniIpAuuB7eyNahMZOBEJeI0uT+xGEXwXiAlj3ejRYop5gdkcflwIjTQ2CRjEf//6vHVzXCQZ8UBv5mDkXMqJA3erKuXEjlqcWlWZBzK0fiidVX/6LI+z5CdZxCfY9rxt3xTkaE5D7MiWfzju6S92/9r8jsGynkUQclv3UMTp/l0n9F5yJRP6ir2/VWpntORA8fUbR4wwQ2fFAwL3P4r/WQw0BqxfHeCYEmsvZflTSpDck31nzRfQ5zRQGvHvtYXfvo4hfo9v2jCc5Ok2HnpFP7SCwQWRCwayoPB1o9uvF1XcJCnLh7VntLg2EvN7B6UztURvmWfJLp31fl0UIfjK9BfuLwVMrjTA/85VP2JiOwqenws6ii2mut05gaPzP3zgn63mj5Nxla7qehRsytS5YH4aIz7GKcqA1AxUmrao8T3IzrXPA/PKQc9uEMsTIVRCGsjrr81oW/MNYZ3NkUDMtzaVc57mx3o2GI8UR14tkj915qjls+vIlnngt76ZFFBFUgE1ZiVFCmw==
    template:
        metadata:
            annotations:
                reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
                reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
                reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "homepage"
