---
isClusterService: true

fullnameOverride: coredns
image:
  #  repository: mirror.gcr.io/coredns/coredns
  repository: coredns/coredns
  tag: 1.14.1@sha256:82b57287b29beb757c740dbbe68f2d4723da94715b563fffad5c13438b71b14a

serviceAccount:
  create: true

service:
  ipFamilyPolicy: "PreferDualStack"
  clusterIPs:
    - "2001:cafe:43::a"
    - 10.43.0.10
prometheus:
  service:
    enabled: true
  monitor:
    enabled: true

replicaCount: 2

servers:
  - zones:
      - zone: .
        scheme: dns://
        use_tcp: true
    port: 53
    plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      # - name: rewrite
      #   parameters: name substring idm.${SECRET_DOMAIN} external.network.svc.cluster.local
      - name: rewrite
        parameters: name substring idm.${SECRET_DOMAIN} kanidm.kanidm.svc.cluster.local
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods verified
          fallthrough in-addr.arpa ip6.arpa
      - name: autopath
        parameters: "@kubernetes"
      - name: forward
        parameters: . tls://1.1.1.1 tls://1.0.0.1 tls://2606:4700:4700::1111 tls://2606:4700:4700::1001
        configBlock: |-
          tls_servername one.one.one.one
      - name: cache
        configBlock: |-
          prefetch 20
          serve_stale
      - name: loop
      - name: reload
      - name: loadbalance
      - name: prometheus
        parameters: :9153
      - name: log
        configBlock: |-
          class error

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
