---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/bitnami.com/sealedsecret_v1alpha1.json
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-secret
  namespace: media
spec:
  encryptedData:
    api_key: AgAKiznJCsbaqndTuhy6gExls7ao0iw1EuLFu5DuhWNE4Gquwze0fcU1ofA3E8MEyCMZtXJ3BAbJTHCGHmoEmszIsKY7UllpVTM5aiPDbuSrCp+nfClgag35d0ZcEk7Li+LvAbuOmK57D6Rd295EcN7muuj3h/fQc7s+QPonisr+F+U53LaZWEJbmmQ53iR4VlQKmcaPsMg3Zun3KdBxSS8ZmpuRJeqxWeOTRpYrimZpYrVE4CW0XlIbmLwdv5FepBrwDxH/putUc+68TiQfzsWBytqTBENcbFXmqujhm7Q3/MuPPCpyH6T6tojzBaKN+4nTr6ECtvxObHvQsIPMeiu6PHBW7bIRUyhRJIHX5edioctQnrCEPBmU/lHBgXw8swai9SuaCo+d3J0UefH1dooh0APTSc4lZDPvKA68tJTRihyD4wZHnK7Zf7DyG2JNiOQxX2g6yy+wK50+sFYCJtkTct3ATtHuikiO5uVTlzSd5Kp35Nt/tUISw+O60SM2eB4l7JU+H+J3XIfqh+LDschkoxLNTstoliHE683kchRlRo8iYFNa9YKiwJbslvi0d11zSkiKopsTI2jVXtveno6CH1ns1W63ahBBxuVp5wuNIBQmioagad3ccTAp29EHUUEOfMGTebNzWEi9Wy5wOEBLSvHKYMsk4jGizSAFvWiryuAFWhoH4F4ZF8XR95JJVkUTf6IOMS+m/sw43FZX1bupRWzxOyLzyzHSxaVUnmj96g==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "homepage"
