---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app opencloud
  namespace: &namespace opencloud
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/oidc
  #    - ../../../../components/volsync
    - ../../../../components/gatus/external
  #  dependsOn:
  #    - name: volsync
  #      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/opencloud/opencloud/app
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      SUBDOMAIN: cloud
      OIDC_PUBLIC_CLIENT: "true"
      OIDC_DISPLAY_NAME: "OpenCloud"
      OIDC_CALLBACK: /oidc-callback.html
      OIDC_EXTRA_CALLBACKS: '["https://cloud.m00nlit.dev/oidc-silent-redirect.html"]'
      OIDC_SHORT_USERNAME: "true"
      OIDC_CLAIM_MAPS: |
        {
          "roles": {
            "joinType": "array",
            "valuesByGroup": {
              "users@idm.m00nlit.dev": ["user"],
              "admins@idm.m00nlit.dev": ["admin"]
            }
          }
        }
      OIDC_CUSTOM_STATE: |
        {
          "systems": {
            "oauth2": {
              "OpenCloudDesktop": {
                "displayName": "OpenCloud",
                "originUrl": [
                  "http://localhost",
                  "http://127.0.0.1"
                ],
                "originLanding": "http://localhost",
                "removeOrphanedClaimMaps": true,
                "public": true,
                "preferShortUsername": true,
                "enableLocalhostRedirects": true,
                "scopeMaps": {
                  "users": [
                    "openid",
                    "profile",
                    "email"
                  ]
                },
                "claimMaps": {
                  "roles": {
                    "joinType": "array",
                    "valuesByGroup": {
                      "users": [
                        "user"
                      ],
                      "admins": [
                        "admin"
                      ]
                    }
                  }
                }
              },
              "OpenCloudAndroid": {
                "displayName": "OpenCloud",
                "originUrl": [
                  "oc://android.opencloud.eu"
                ],
                "originLanding": "oc://android.opencloud.eu",
                "removeOrphanedClaimMaps": true,
                "public": true,
                "preferShortUsername": true,
                "enableLocalhostRedirects": true,
                "scopeMaps": {
                  "users": [
                    "openid",
                    "profile",
                    "email"
                  ]
                },
                "claimMaps": {
                  "roles": {
                    "joinType": "array",
                    "valuesByGroup": {
                      "users": [
                        "user"
                      ],
                      "admins": [
                        "admin"
                      ]
                    }
                  }
                }
              },
              "OpenCloudIOS": {
                "displayName": "OpenCloud",
                "originUrl": [
                  "oc://ios.opencloud.eu"
                ],
                "originLanding": "oc://ios.opencloud.eu",
                "removeOrphanedClaimMaps": true,
                "public": true,
                "preferShortUsername": true,
                "enableLocalhostRedirects": true,
                "scopeMaps": {
                  "users": [
                    "openid",
                    "profile",
                    "email"
                  ]
                },
                "claimMaps": {
                  "roles": {
                    "joinType": "array",
                    "valuesByGroup": {
                      "users": [
                        "user"
                      ],
                      "admins": [
                        "admin"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
