---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/tor.k8s.torproject.org/tor_v1alpha2.json
apiVersion: tor.k8s.torproject.org/v1alpha2
kind: Tor
metadata:
  name: tor-proxy
  namespace: default
spec:
  client:
    socks:
      enable: true
      policy:
        - "accept 2001:cafe:42::/56"
        - "accept 10.42.0.0/16"
      flags:
        - IsolateClientAddr
        - IsolateSOCKSAuth
  config: |
    MapAddress palladium.libera.chat libera75jm6of4wxpxt4aynol3xjmbtxgfyjpu34ss4d7r7q2v5zrpyd.onion
    MapAddress irc.oftc.net oftcnet6xg6roj6d7id4y4cu6dchysacqj2ldgea73qzdagufflqxrid.onion
