---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
openapi:
  path: http://crd-patcher.default.svc/definitions.json?crd=helm.toolkit.fluxcd.io.v2.HelmRelease&extraProp=helm.toolkit.fluxcd.io.v2.HelmRelease:spec.values.defaultPodOptions.schedulingGates
patches:
  - target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: not-used
      spec:
        values:
          defaultPodOptions:
            annotations:
              k8s.ksgate.org/dragonfly-ready: |
                {
                  "apiVersion": "apps/v1",
                  "kind": "StatefulSet",
                  "name": "dragonfly",
                  "namespace": "database",
                  "expression": "resource.status.readyReplicas >= 1"
                }
              k8s.ksgate.org/dragonfly-service: |
                {
                  "apiVersion": "v1",
                  "kind": "Service",
                  "name": "dragonfly",
                  "namespace": "database"
                }
            schedulingGates:
              - name: k8s.ksgate.org/dragonfly-ready
              - name: k8s.ksgate.org/dragonfly-service
# asd:
#           persistence:
#             postgres-certs:
#               type: secret
#               name: "postgres-{{ .Release.Name }}-cert"
#               defaultMode: 0440
#               globalMounts:
#                 - path: /var/run/secrets/postgresql
