---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./httproute.yaml
  - ./karakeep.yaml
  - ./karakeep.sops.yaml
  - ./mcpgroup.yaml
  - ./searxng.yaml
  - ./virtualmcpserver.yaml
