---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/toolhive.stacklok.dev/mcpgroup_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPGroup
metadata:
  name: mcp-tools
spec:
  description: Aggregated MCP tools for AI assistants
