---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tor-controller
spec:
  interval: 1h
  url: https://bugfest.github.io/tor-controller
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tor-controller
spec:
  interval: 1h
  chart:
    spec:
      chart: tor-controller
      version: 0.1.17
      sourceRef:
        kind: HelmRepository
        name: tor-controller
        namespace: tor
