---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cdi.kubevirt.io/cdi_v1beta1.json
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    featureGates:
      - HonorWaitForFirstConsumer
      - WebhookPvcRendering
  imagePullPolicy: IfNotPresent
