---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ${APP}-postgres
spec:
  refreshInterval: "0"
  target:
    name: *name
    template:
      engineVersion: v2
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "postgres"
        labels:
          cnpg.io/reload: "true"
      data:
        username: "${DATABASE_OWNER:=${APP}}"
        password: "{{ .password }}"
        host: "pooler-rw.postgres.svc"
        database: "${APP}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: pw
