# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: qui-secret
stringData:
  QUI__SESSION_SECRET: ENC[AES256_GCM,data:59UVOnj4sftZP071CMz4nq0N0LFdWQQYPE5ObF+T0xJ+3QbMCcxp9q5Vs9wuSR1McVWpDzgBPGLuZDno4T6MtQ==,iv:Pb/aMAZmiGDeUzwQYsOo87BiRG8hNykiDMJ+E8XiC7w=,tag:dYMN6ibu/aowKPRQ4342rA==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeGp1SFFLL0sxNDUyVTZu
        b25aVzcyZkhvRlZlalBMUnBxL0JRdlFsemxBCmRlNlhZeVVPQlBGT2h1ODBBVUo2
        SFU0ZGl0TkZrTWxCMjNCQ1RHcjBRRW8KLS0tIEd2d01lUzhHYjB2VGJMSGZvRGJz
        dFN1WTBaUnpGNmVkWE5Cd2w2MkJNUEEKW3Q1HZPjzvy0XTRx9dQGXbZ4Hh/Uwb5g
        E/ji6Rqgc8diu/LTfjvJV2mcuvVQYq1fiibx8G4SaTtb8ngROSXKiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T17:58:32Z"
  mac: ENC[AES256_GCM,data:R7UG2w7EdeqNJJ5qOBM2UK1WrOH6gVA80ZFlDg7fRDcTx7nLqC9qrpT8oQVB06DD8TSGvazk3QQQkuZGKqa03jtqbv/DvmXJ5LQpzVHmmmEjEk4uGp2Xrf5BzNaShX3oqIatPVbUaKCr6peFnY2+i+qwG5HxNuCCAQZNR+Wz8Cc=,iv:nJOZ6IcnuH9Q6A3bj+B7dhzFiKIafYYmd1dAVvrmdfI=,tag:3QhUp9z4gU2TGAxNeRyaCQ==,type:str]
  pgp:
    - created_at: "2025-06-22T23:50:49Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdADCKNPgyDqATq7NWB27t0yW/NjTPgLZ4EoDytfVt2MxIw
        B8enMkoeQzd1szUZDlWUXeWVlwym+DERtWGFm0UaGDANrI7vmzOt5SepIIztaJD0
        0l4BXOxLcVqdWDCBiDw3vE9FSdx8jgNzrIUucBYQCP9b12G3rgnYfoJq6IxDrh+S
        PdFvm6AgjCZ05GWuSWZ7pgZ09aoB13X002J+DlYuUJxbACgv+NbE9ITeiS9WrDFa
        =HrGc
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
