---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${APP}-db
  namespace: &namespace postgres
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app ${APP}
  dependsOn:
    - name: cnpg
      namespace: cnpg-system
  interval: 1h
  path: ./kubernetes/components/database/base/postgres
  postBuild:
    substitute:
      APP: *app
      OWNER: ${DATABASE_OWNER:=${APP}}
      EXTENSIONS: ${q:='}${DATABASE_EXTENSIONS}${q:='}

      emptyArray: "[]"
  healthChecks:
    - name: postgres-${APP}
      namespace: *namespace
      kind: Database
      apiVersion: postgresql.cnpg.io/v1
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
