---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kanidm-${APP}-oidc
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app ${APP}
  dependsOn:
    - name: kanidm
      namespace: kanidm
  interval: 1h
  path: ./kubernetes/components/oidc/base/kanidm
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: ${NAMESPACE}
      SUBDOMAIN: ${SUBDOMAIN:=${APP}}
      CALLBACK: ${OIDC_CALLBACK:=/oauth2/callback}
      ORIGIN: ${OIDC_ORIGIN:=/}
      DISPLAY_NAME: ${OIDC_DISPLAY_NAME:=${APP}}

      PUBLIC: "${OIDC_PUBLIC_CLIENT:=\"false\"}"
      SHORT_USERNAME: "${OIDC_SHORT_USERNAME:=\"false\"}"
      LEGACY_CRYPTO: "${OIDC_LEGACY_CRYPTO:=\"false\"}"
      DISABLE_PKCE: "${OIDC_DISABLE_PKCE:=\"false\"}"

      CUSTOM_STATE: '"{}"'
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kanidm
  timeout: 5m
  wait: false
