apiVersion: v1
kind: Secret
metadata:
  name: garage
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:MqZGdWwGN7zG2k3tBBmYvtoneFeIh10EiNs=,iv:zcZtfeGwX4QpNmM1QM4jdR2p4QUVoiLKnnhdVeCN19s=,tag:PzZuSYvo+Es2bgBjX31/WA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:UjM+K2Yc67m9qTf4aUYwVfTTKm0meACR+8HGWl7QR+/sUtpaLDYDh2ZFrETav+YeY5u0AcvC6p37xigaEOppjQ==,iv:fheltYco5buXenSo5XGx8sqCdZ9vYnKIGKHBF0PsLbo=,tag:DSPvim0EAGRS9FFbQcIOlA==,type:str]
  REGION: ENC[AES256_GCM,data:eTpx8KHq,iv:Fn4wZ3TgtTG51r4PKjtZgct78tyPZRF69GY0ApGtPig=,tag:MxrLUdbFh6NYFEKkWgNHzQ==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUVZ0QW04cGI5ZldlVnFQ
        OXlxVkhVdEprMHB5cUxSUGdSd0ZCZGgxREFVCkUvQjYxUG45Q2JOMVNDWWh4Tzl6
        WXYydXhqdXA3Q2VmVkRnVk9wRmJFd1EKLS0tIGMrb2lXcE9oUW40TW5LeXRFdCtP
        RVhlN0ZVbmVrZjdrbVFJdGxVRjgzNGMKyUW4a/sEKPX1XoDp5MqDquL7CqBr9oPj
        B6wm24EnJy5Nty6wR0py6vMDpIxdShmRpjIzsGFz+hB9E8bVa6RUQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T14:22:37Z"
  mac: ENC[AES256_GCM,data:zn8OSX9LNwGctQ7cIlAb7Ea7TEwvltIUm5G+jumkGViCHokuv1uz3j3Nv4s2Q84rDehGJaUebaDCXkpp5yi2V+AN3a7Gb7kHUABvKl6oAJntj0Dv0U62Z4LoacQ4sRS6btJwq0Ey7wtH/Vz5EGkOnhmkxQWYZFqzIf8mLh7Qwxc=,iv:I7jZgsIxpFS5XsdahSnsmelg1+Q13T8bl8qUqDQRDi0=,tag:x38Ny/vFzGpPLPAlDDzseQ==,type:str]
  pgp:
    - created_at: "2025-06-17T23:44:18Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdA0MxRxW9NvjyhUIH6fgkcz4EBgheqctmsvB6ZLGkifAow
        d7x3y96HzJLydLwBgH+YvP6LxYvze6JrQal4qzfTUl01NoSLiTLAcACMYONcAFOs
        0l4BPK4vZdjRSdBTinSOpJI51N3dtR7ZLwTN0a1bWB9ElZw66pBNvOEBvUPDuzxT
        c3TWB5PDEePqd94VUjD8otZjpgSS8rN/oA4E0JeD+9EkjvE7eQj6qIsO9aO0eYGF
        =4mWc
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
