---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
spec:
  isCA: true
  commonName: cluster-ca
  subject:
    countries:
      - PL
    organizations:
      - homelab-cluster
  usages:
    - cert sign
    - crl sign
  nameConstraints:
    critical: true
    permitted:
      dnsDomains: &domains
        - .svc.cluster.local
        - .cluster.local
        - .svc
        - postgres-rw
        - postgres-ro
        - postgres-r
      # Private IP space only
      # ipRanges:
      #   - 10.0.0.0/8
      #   - 172.16.0.0/12
      #   - 192.168.0.0/16
      uriDomains: *domains
  duration: 87660h # 10 years
  privateKey:
    # .net core somehow still doesn't support Ed25519, despite there being multiple
    # decade-old requests for it. C# service cannot verify cert chains that contain
    # ANY Ed25519 certs, so it can't be used for the root CA.
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Never
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: cluster-ca-cert
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-ca
spec:
  ca:
    secretName: cluster-ca-cert
