---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: &namespace automation
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/oidc
    - ../../../../components/volsync
    - ../../../../components/database
    - ../../../../components/gatus/guarded
  dependsOn:
    - name: volsync
      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/automation/home-assistant/app
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      SUBDOMAIN: hass
      DATABASE_OWNER: hass
      OIDC_DISPLAY_NAME: "Home Assistant"
      OIDC_CALLBACK: /auth/oidc/callback
      OIDC_ORIGIN: /auth/oidc/welcome
      OIDC_SHORT_USERNAME: "true"
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
