---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/stunner.l7mp.io/gatewayconfig_v1.json
apiVersion: stunner.l7mp.io/v1
kind: GatewayConfig
metadata:
  name: stunner
spec:
  logLevel: "all:DEBUG,turn:INFO"
  realm: stunner.l7mp.io
  authType: static
  userName: "user-1"
  password: "pass-1"
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/gateway.networking.k8s.io/gatewayclass_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: stunner
spec:
  controllerName: "stunner.l7mp.io/gateway-operator"
  parametersRef:
    group: "stunner.l7mp.io"
    kind: GatewayConfig
    name: stunner
    namespace: network
  description: "STUNner is a WebRTC ingress gateway for Kubernetes"
