---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &app stunner
  labels:
    metrics: *app
spec:
  podMetricsEndpoints:
    - honorLabels: True
      interval: 5s
      port: "metrics-port"
      path: "/metrics"
  selector:
    matchLabels:
      app: *app
  namespaceSelector:
    matchNames:
      - network
