---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app ${APP}
spec:
  secretStoreRef:
    kind: SecretStore
    name: k8s-store-matrix-ns
  target:
    name: "${APP}-config"
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: "mautrix-meta-configmap"
            items:
              - key: config.yaml
  dataFrom:
    - extract:
        key: *app
