apiVersion: v1
kind: Secret
metadata:
  name: slskd-secret
stringData:
  SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:pVJ2imZ8PIyGSXK3,iv:MOSf+/rsi5yDM9FmlQtI0YSL87azfWyF5mpsRR1NKVk=,tag:deUukuAUdz7337TocXoOfw==,type:str]
  SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:ogMUl4JF6Q51XnOjYp6kMFYqLa8VzZVise9itA7WHac=,iv:wy8xIP385pvCdDg+iPzeWBrn/oC0kbRvtvQUYlKllJA=,tag:pbt15iSTif6EYLN5CkMUEA==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2THoyLzM0a2h3U0hiVzhq
        aFZ0T0xBb2htVzdJZjcySFo1dkhNTFZ6NzFjCkhMUnZVeEpFK1E2WVNWazdvNlEx
        VlRKQ3lOdldDMHVZM3RMQ01PZmJ4VTgKLS0tIGt0N2kyS2pRcWVrclRkR1EzRE1X
        MjdIZ3V4dXBjWGdFd3J3SkprNVpkSE0Kh3gtAqanmQEE9pGNCKHoKQGbWXFlQNtP
        /MCm8PaFbJPvaJ5DjzrzPdVq2JTcAhfxm+DtesNGIAjSXWcPsd65ZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T22:23:39Z"
  mac: ENC[AES256_GCM,data:NwYoG8bhdsV3Tx85oY8MmUsnfiuqm0x7Sg24zv8ByS+VuP0i0XTUTs46uxjp3yr+DD7wSbGzY6hqtHDWdgmIRvDz0KHX86RIK3+J4YJpMOGcN6RjBWzAH30niPXx2yxu6RjSM3SnI6fZslu6fNQtAQj73OPOJ7yh1lhkdbm4zQU=,iv:c2apNEkpQpwLLUvr6wUf9H9v7OS3wLGB+LKzAi4obsg=,tag:DkK+23iQaVkvV4vUWsergg==,type:str]
  pgp:
    - created_at: "2025-10-25T20:57:49Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdABFOkLeMQeZBvsnFqHekLD7mzbrxHDCzy/y7/FXbh8y8w
        iUJfZKpOMJ57pHyYUIy8TIDJl1d2E3yRFUNtxiTgg86XUZFgkxzWBbQ66brWb5nf
        0l4BfDB6zh1/js4QJot7r0zfkxbD6BeNkLhD321VvaPI5bVrDpZ7xX3/r8nTF4VM
        8fJlxV1j0x9842cgX24AhHLebBTn12zVLc02se2M8r3Hko7cLoSHHzEuZIGZpqjR
        =dALJ
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
