apiVersion: v1
kind: Secret
metadata:
  name: slskd-secret
stringData:
  SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:RMxgmsU=,iv:jBzOEnEqUvBCpvsaFv9rzuHjk9+7li/1hLmcYD44xos=,tag:VSg81Yau5VveFwuuS+J9Qw==,type:str]
  SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:Eud4exI=,iv:uZKRojhDDfct/2iox5ac5+t7SFJzYXUTDaNQWDPBlSI=,tag:beWU1kJUaYgBziE2arjtnw==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2THoyLzM0a2h3U0hiVzhq
        aFZ0T0xBb2htVzdJZjcySFo1dkhNTFZ6NzFjCkhMUnZVeEpFK1E2WVNWazdvNlEx
        VlRKQ3lOdldDMHVZM3RMQ01PZmJ4VTgKLS0tIGt0N2kyS2pRcWVrclRkR1EzRE1X
        MjdIZ3V4dXBjWGdFd3J3SkprNVpkSE0Kh3gtAqanmQEE9pGNCKHoKQGbWXFlQNtP
        /MCm8PaFbJPvaJ5DjzrzPdVq2JTcAhfxm+DtesNGIAjSXWcPsd65ZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T22:10:34Z"
  mac: ENC[AES256_GCM,data:VKAcgGkoXo07G5U7kkQ289px98FXEMzH4LCUq0lQgNSP8ybupau90XpoQZ2QNHjYmfGTIbbb0g33ATd766HyWRyfbxaILPhhBYC3+hs21wGXnIB/QNpCLDR0yDnrP54ergpJnEoAbyKGJwLii3Z9JNq67E2UM+S1RvwbMqTu7oM=,iv:nF0QChAm9iiNlZAWuDLEd80QnEvt6zcIR0Yyo4ATbkA=,tag:bGRVJ0PAx+97gX4EuuAWvA==,type:str]
  pgp:
    - created_at: "2025-10-25T20:57:49Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdABFOkLeMQeZBvsnFqHekLD7mzbrxHDCzy/y7/FXbh8y8w
        iUJfZKpOMJ57pHyYUIy8TIDJl1d2E3yRFUNtxiTgg86XUZFgkxzWBbQ66brWb5nf
        0l4BfDB6zh1/js4QJot7r0zfkxbD6BeNkLhD321VvaPI5bVrDpZ7xX3/r8nTF4VM
        8fJlxV1j0x9842cgX24AhHLebBTn12zVLc02se2M8r3Hko7cLoSHHzEuZIGZpqjR
        =dALJ
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
