apiVersion: v1
kind: Secret
metadata:
  name: krr
stringData:
  FORGEJO_TOKEN: ENC[AES256_GCM,data:eE99N/Xca8RUJ8Q8XoyKE8l/TU2oFXFTZKW3iJyhFTL7FnJcFS1d/Q==,iv:ptlDBOgkeHvq9J7Mp5XQ+5AnAYwV3muJ9ViPntGsc08=,tag:PLe4iub+EhylBTc0VlM81A==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOXdLZXQvMVEyWHpLOGNi
        K1RpVitVNVFYVzF1aGRiWHVNSXkvRDJaY2lnCmtLWXppek5wWEUwcUtPdjRSb3Ux
        TlZOUGFYb1RoUFFCRkt3M1V3bUJlYjgKLS0tIE1ibkNZa0tYNWp1eGpxQ21wT2t2
        eldXb1JnWVRyYzVYUmZ1TDdudUxUVFkKL6/flM5op3iebmug3f9H2pqzNc2Hdl5B
        qdIgWw2od3DXhLKIQyrfxJ4nMOAXfdvx/iBUtuEYTtkADD9cBomA+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T20:43:29Z"
  mac: ENC[AES256_GCM,data:R/tphB368pq/UAK0YN74jsYA4p159MJaBYUFZ+diXqb3ZeaKW/d5RSL+ITwYse+sR36ESUbxpv6wgSnraqMRyjqg6njfFIq/+iaQTRSrXylneJVxKNwoX7ERr9GBYvGv2N8Q/4/FQHyOf58JcBh8Snk3Qu9FzbeOePTpEiiZHDM=,iv:JeFeCtGnvp1xlFJSoxwd4BnXa888qLPMUtc3jt5qBJ8=,tag:3MaXcO2tomv1SGPiJCmwbg==,type:str]
  pgp:
    - created_at: "2025-09-02T12:35:45Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdAeE1Bf1RqiF+CVUql8K65jgnV8m1CzMGyAWsS0lA5NAcw
        5Ws1mqartoYovD24zFBUZ68EVCUB5EQbFaTccBkP3kgJwO8OcnYLPIawo+HI9tze
        0l4BY8S+8qr+VsU/HKsfPcBESu/H2VEBu1NP+XkDsymaH4u5uWc52afu+p1eyqww
        GGB2mb3MYrWha2I7YYxxAyPv78uWyiJ0lm0vpSXiuhLxWtUulOMfdhJEsfdGdY0g
        =Kpff
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
