---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/scheduling.k8s.io/priorityclass_v1.json
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: envoy-gateway-priority
value: 1000000
globalDefault: false
description: "Higher than app workloads; below system-critical."
