---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-${APP}
  namespace: postgres
spec:
  name: ${APP}
  owner: ${OWNER}
  cluster:
    name: postgres
  extensions: ${EXTENSIONS:=${emptyArray}}
