apiVersion: v1
kind: Secret
metadata:
  name: volsync-template
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UpPhIrYC3IvJgGMEHD7gA/qKOXK9g8FJkJo=,iv:VuGFAWAtXvQGDOqC5qdREXcVFl9GRmzzZOx9jIhxQbQ=,tag:WlIBk9itxkIHMzY0eVTi4Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xCx5OWKyzWveaKfc9WMNnzUHBqNxRYSaeQU1UsUAybcemmcQP21Q4yoRjjCHvj5BYNrNuu24wCoP0x8CXfuF7Q==,iv:R8u7o18AmAFdAPcFy+Xg2zJgfTC40cqtVrMr/kUTAyM=,tag:W6FZZfE4n0JMi+m9Q2sFEA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:vm59MWTTviyg6XgFFNBQeh6hzyAW/tjR9u4XUZVThg5qLByvtMvmqkhyW1IfR58pay42o42ieOPZ2H89U0YJiUeCaLOMl3X6aVGRG79C580XhwQ53jLOtDGne0CRrrGAZTYXCcatkAGQE8gg+p8jSJTQfcBgZYaoUO92tcPV5l0=,iv:tL92IIhJS77eHTW+q02pjE02I91AzRz76GRl+y0QRYM=,tag:/OH6nZeVh0fBwSUglFAaEQ==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUVZ0QW04cGI5ZldlVnFQ
        OXlxVkhVdEprMHB5cUxSUGdSd0ZCZGgxREFVCkUvQjYxUG45Q2JOMVNDWWh4Tzl6
        WXYydXhqdXA3Q2VmVkRnVk9wRmJFd1EKLS0tIGMrb2lXcE9oUW40TW5LeXRFdCtP
        RVhlN0ZVbmVrZjdrbVFJdGxVRjgzNGMKyUW4a/sEKPX1XoDp5MqDquL7CqBr9oPj
        B6wm24EnJy5Nty6wR0py6vMDpIxdShmRpjIzsGFz+hB9E8bVa6RUQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T14:21:09Z"
  mac: ENC[AES256_GCM,data:gw+2PB+qgDw4u8bCCXtr3fj50eUYEmZMcZflFIF7wqdE0gSSNlJDZRoMp81Uib+R+MDQnXKVvXzBa608nyZfs4/51ikXHHsF1OMMkZ1ZPSLCXSco+jnfqn++VBJv6aQxpcw7D66xlvj+hL6YYH9VKffxtogQGLQqqrbqIcKL80g=,iv:t+YOOA1OBXpGamAzE6B/8fJ18zocsff+N6ccZ115QM0=,tag:ezW+o8LQWo0Ukd1LQ5ztEg==,type:str]
  pgp:
    - created_at: "2025-06-17T23:44:18Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdA0MxRxW9NvjyhUIH6fgkcz4EBgheqctmsvB6ZLGkifAow
        d7x3y96HzJLydLwBgH+YvP6LxYvze6JrQal4qzfTUl01NoSLiTLAcACMYONcAFOs
        0l4BPK4vZdjRSdBTinSOpJI51N3dtR7ZLwTN0a1bWB9ElZw66pBNvOEBvUPDuzxT
        c3TWB5PDEePqd94VUjD8otZjpgSS8rN/oA4E0JeD+9EkjvE7eQj6qIsO9aO0eYGF
        =4mWc
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
