---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/metallb.io/ipaddresspool_v1beta1.json
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public
spec:
  addresses:
    - 2a02:a313:43e4:7080::200/120
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/metallb.io/ipaddresspool_v1beta1.json
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: private
spec:
  addresses:
    - fd42:78a5:2c09::200/120
    - 192.168.0.192/26
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/metallb.io/ipaddresspool_v1beta1.json
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: reserved
spec:
  addresses:
    - 192.168.0.53/32
    - fd42:78a5:2c09::53/128
  autoAssign: false
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/metallb.io/l2advertisement_v1beta1.json
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-policy
