---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: multus-crd
spec:
  interval: 30m
  url: https://github.com/k8snetworkplumbingwg/network-attachment-definition-client
  ref:
    tag: v1.7.7
  ignore: |
    # exclude
    /*
    # include
    !artifacts/networks-crd.yaml
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus-crd
spec:
  prune: true
  sourceRef:
    kind: GitRepository
    name: multus-crd
  wait: true
  interval: 15m
  retryInterval: 1m
  timeout: 5m
