apiVersion: v1
kind: Secret
metadata:
  name: anubis-key
stringData:
  ED25519_PRIVATE_KEY_HEX: ENC[AES256_GCM,data:eMQgoGBFFHofGFTzynFeAxXMS1Ge+UePhj5+XpOt2AEXgSOYSW5Va3D/Dx2jnb/RunFqYHj9whvqzYnF39CSBw==,iv:JkW09xM+a6OkFJ9mgDNlfIfWQ5CJB4Z4hKoXSaa9ZNA=,tag:dHkWSduE/uY0civ9xwLfZg==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOXdLZXQvMVEyWHpLOGNi
        K1RpVitVNVFYVzF1aGRiWHVNSXkvRDJaY2lnCmtLWXppek5wWEUwcUtPdjRSb3Ux
        TlZOUGFYb1RoUFFCRkt3M1V3bUJlYjgKLS0tIE1ibkNZa0tYNWp1eGpxQ21wT2t2
        eldXb1JnWVRyYzVYUmZ1TDdudUxUVFkKL6/flM5op3iebmug3f9H2pqzNc2Hdl5B
        qdIgWw2od3DXhLKIQyrfxJ4nMOAXfdvx/iBUtuEYTtkADD9cBomA+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T17:51:27Z"
  mac: ENC[AES256_GCM,data:vadcX1kkLrQLRmHJKVwtdFdB38QbZan1g4hzzEFFDulIqLPKDoZEGqOUFuyBvpQSn77+WQKR/ii456IdaVFudxd+AiR4cnH31ZlK7VSc8yyLjvSYbgeEGIddPh/na3XmDGD6n8ktF7qSewvExodnhzukyyWp5L1l4E0/sUZs5XA=,iv:H2yRLvx6egG2ofO4mmkbOBviBKxc0d0iDQPWJrfOeOU=,tag:e2utX2cynKCTjAPg21Q6ZQ==,type:str]
  pgp:
    - created_at: "2025-09-02T12:35:45Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdAeE1Bf1RqiF+CVUql8K65jgnV8m1CzMGyAWsS0lA5NAcw
        5Ws1mqartoYovD24zFBUZ68EVCUB5EQbFaTccBkP3kgJwO8OcnYLPIawo+HI9tze
        0l4BY8S+8qr+VsU/HKsfPcBESu/H2VEBu1NP+XkDsymaH4u5uWc52afu+p1eyqww
        GGB2mb3MYrWha2I7YYxxAyPv78uWyiJ0lm0vpSXiuhLxWtUulOMfdhJEsfdGdY0g
        =Kpff
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
