# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: migadu
stringData:
    MIGADU_USERNAME: ENC[AES256_GCM,data:Xb5+/wAj0SZdI5ylcK+/kQ==,iv:GXWbpoGRI/3y9365/2RDrcteKVt6ufFu0Ou5na9bE+4=,tag:QDZJaG0sREMYYCJA7dQvbQ==,type:str]
    MIGADU_TOKEN: ENC[AES256_GCM,data:VaU8LPw9tgRUIRWGlC4DW9Bv1mNUkfPEg+0FQBUGnkdhpD5rh2Voq6RiW0+y+SlchBlwZlpBKsXL5VcsxDJdSHWgyIQPq8VEpOUjwYNbtkCrlhdTz1M=,iv:ekrX8BNXRZmfdXYhAXLzXf1mqPYRS1Q4IGfzsdoeZYc=,tag:fvCc1B5iJJcKowlrsHyM3g==,type:str]
sops:
    age:
        - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVDI1U1dMOEFyb2tXVXYr
            Mnh1ZDZmRUlQWXRKaUJXdjhYVmpvZ0FkUHpnCndSbVpyby9ZVERaQXc0ZllBa1dy
            RHh1QmhnZzJyT0Jxd1ZOVlVCZ1F3YkUKLS0tIFZwNitXUDk3YnQ1Rm1tZ0E5bjJu
            Szl5enFiNm4xNW1tbDYyTUlxQUZ0djQKS+sH5u+LsX4Armk9ltM0hV26hWkze5aK
            4B5B8gpwjc9OQMEXsGqZdHc70LNNvoV2bL82MaGkwELHxOnkoiiiiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T05:48:40Z"
    mac: ENC[AES256_GCM,data:3u3Ailu+duisWpmliYYhSrwp61iaJE+drLMyPjZHK4wp5YaYQWql20aaz9SeRvL1FGcCI39TgF+ZCLxd4quWTAH6mV9U20cTJ5V0og8hApPmKwRj4dvJOuIu831Cp+1ZwDHMm69kxDdSSkbs6xuhnXaV0Xt+0y2FnUcHlRoL1Q0=,iv:8aUidcFbm6ghziLWI7AGAcHR5tZNMx086bcgUtnzKDk=,tag:C1EHQQyiKXlZae6XTK7Jug==,type:str]
    pgp:
        - created_at: "2025-06-15T15:33:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC0EwVK2S0BUSAQdAOuMYTROy4rnQzA8puaM/2nJ9vAZxpc7ZLnH6pIZdtmww
            Pu7AArkzUmd43oNPz+5OPQZ4KeNNgOyyP08VTHJFUK+GjSg6I22feCiHClE7WnSj
            0l4BlEEUwh0+xBy6Bum0xYCphBbFB+VGcWnuxRV93N9Pwcs3ALi7aGxLKVSM+cz5
            JVcAquAbz0FHv6ql1jDAp1oc4mo8shD+TcUqJptghEGDrsp5n96H/wZuK4Nf5WIG
            =zxTx
            -----END PGP MESSAGE-----
          fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
