# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: migadu
stringData:
    MIGADU_USERNAME: ENC[AES256_GCM,data:Xb5+/wAj0SZdI5ylcK+/kQ==,iv:GXWbpoGRI/3y9365/2RDrcteKVt6ufFu0Ou5na9bE+4=,tag:QDZJaG0sREMYYCJA7dQvbQ==,type:str]
    MIGADU_TOKEN: ENC[AES256_GCM,data:MhflAIcGg1fy6GAlM3+dpuTY4HmLR8X18RRluspzAd9+rPonWCuiXVIqcBkPdBjpWHhyr40HMeuapo36C/0Xf/vtURrhPmZjq1PXNfafsQ==,iv:qpVXMBx3KaC/5UKfMWekEVCz7LOSpoxtkGdlW9H99Zo=,tag:SoTVoptWixGSomacNPb3/A==,type:str]
sops:
    age:
        - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVDI1U1dMOEFyb2tXVXYr
            Mnh1ZDZmRUlQWXRKaUJXdjhYVmpvZ0FkUHpnCndSbVpyby9ZVERaQXc0ZllBa1dy
            RHh1QmhnZzJyT0Jxd1ZOVlVCZ1F3YkUKLS0tIFZwNitXUDk3YnQ1Rm1tZ0E5bjJu
            Szl5enFiNm4xNW1tbDYyTUlxQUZ0djQKS+sH5u+LsX4Armk9ltM0hV26hWkze5aK
            4B5B8gpwjc9OQMEXsGqZdHc70LNNvoV2bL82MaGkwELHxOnkoiiiiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T05:15:20Z"
    mac: ENC[AES256_GCM,data:mZm2LQ4uSCkEC/3KZ3Kq9KyU/YFRNNzCHqJT/Q4qWT2KKvySoNM8J/awbxatmQiFPSnm9ikFO3XBlOdm+KeG4Ps8/52sOsIP+SLjMDGlJw4m/IOaGe7n2U7A/l49S5rdELmwCnoF+nD5lDsN5N9mcYC2uhfP0xYIptLOiZ3HSik=,iv:L0U90mWykPQsnVyQEDTAQo+c6v0cI0MIFvlicN3S9gQ=,tag:1I1pZGQshakLvm18sMqy+g==,type:str]
    pgp:
        - created_at: "2025-06-15T15:33:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DC0EwVK2S0BUSAQdAOuMYTROy4rnQzA8puaM/2nJ9vAZxpc7ZLnH6pIZdtmww
            Pu7AArkzUmd43oNPz+5OPQZ4KeNNgOyyP08VTHJFUK+GjSg6I22feCiHClE7WnSj
            0l4BlEEUwh0+xBy6Bum0xYCphBbFB+VGcWnuxRV93N9Pwcs3ALi7aGxLKVSM+cz5
            JVcAquAbz0FHv6ql1jDAp1oc4mo8shD+TcUqJptghEGDrsp5n96H/wZuK4Nf5WIG
            =zxTx
            -----END PGP MESSAGE-----
          fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
