---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app livekit
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      *app :
        #        pod:
        #          hostNetwork: true

        containers:
          app:
            image:
              repository: livekit/livekit-server
              tag: v1.9.11@sha256:289262ffae8b827f45186331aa315d08ed275eb30f9b0add337ec57948e44ca1
            ports:
              - containerPort: 7880
                name: http
                protocol: TCP
              - containerPort: 7881
                hostPort: 7881
                name: rtc-tcp
                protocol: TCP
              #              - containerPort: 443
              #                hostPort: 443
              #                name: turn-tls
              #                protocol: TCP
              - containerPort: 3478
                hostPort: 3478
                name: turn-udp
                protocol: UDP
            env:
              LIVEKIT_CONFIG:
                valueFrom:
                  configMapKeyRef:
                    name: livekit-configmap
                    key: config.yaml

            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true

      jwt:
        containers:
          app:
            image:
              repository: ghcr.io/element-hq/lk-jwt-service
              tag: 0.4.0@sha256:aba31cef052cedbf263f5e642dfb49476f779b46d0244d5b9337022033c4b66d
            env:
              LIVEKIT_URL: wss://livekit.${SECRET_DOMAIN}
              LIVEKIT_KEY_FILE: /config/keys.yaml
              LIVEKIT_FULL_ACCESS_HOMESERVERS: "${SECRET_DOMAIN}"
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true

    #              capabilities: { drop: [ "ALL" ] }
    #            resources:
    #              requests:
    #                cpu: 100m
    #                memory: 1Gi
    #              limits:
    #                memory: 1Gi

    #    defaultPodOptions:
    #      securityContext:
    #        runAsNonRoot: true
    #        runAsUser: 2000
    #        runAsGroup: 2000
    #        fsGroup: 2000
    #        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        forceRename: *app
        controller: *app
        ports:
          http:
            port: 80
            targetPort: 7880
          rtc-tcp:
            port: 7881
          metrics:
            port: 6789

      jwt:
        controller: jwt
        ports:
          http:
            port: 80
            targetPort: 8080

    serviceMonitor:
      app:
        serviceName: app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: *app
                port: 80
          - matches:
              - path:
                  type: PathPrefix
                  value: /sfu
            backendRefs:
              - name: livekit-jwt
                port: 80

    persistence:
      keys:
        type: secret
        name: livekit-keys
        defaultMode: 0600
        globalMounts:
          - path: /config/keys.yaml
            subPath: keys.yaml
