---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app livekit
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      *app :
        #        pod:
        #          hostNetwork: true

        containers:
          app:
            image:
              repository: livekit/livekit-server
              tag: v1.9.3@sha256:75484e317a90991f5e7a8edbc2eb1ee92f690e440c5b7d88a2713b5fa70f368a
            ports:
              - containerPort: 7880
                name: http
                protocol: TCP
              - containerPort: 7881
                hostPort: 7881
                name: rtc-tcp
                protocol: TCP
              #              - containerPort: 443
              #                hostPort: 443
              #                name: turn-tls
              #                protocol: TCP
              - containerPort: 3478
                hostPort: 3478
                name: turn-udp
                protocol: UDP
            env:
              LIVEKIT_CONFIG:
                valueFrom:
                  configMapKeyRef:
                    name: livekit-configmap
                    key: config.yaml

            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true

      jwt:
        containers:
          app:
            image:
              repository: ghcr.io/element-hq/lk-jwt-service
              tag: 0.3.0@sha256:52357326970d3f3e3cf6e9c33766e49cf2665e2cd57842e29a5c298514bd2e58
            env:
              LIVEKIT_URL: wss://livekit.${SECRET_DOMAIN}
              LIVEKIT_KEY_FILE: /config/keys.yaml
              LIVEKIT_FULL_ACCESS_HOMESERVERS: "${SECRET_DOMAIN}"
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true


    #              capabilities: { drop: [ "ALL" ] }
    #            resources:
    #              requests:
    #                cpu: 100m
    #                memory: 1Gi
    #              limits:
    #                memory: 1Gi

    #    defaultPodOptions:
    #      securityContext:
    #        runAsNonRoot: true
    #        runAsUser: 2000
    #        runAsGroup: 2000
    #        fsGroup: 2000
    #        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        forceRename: *app
        controller: *app
        ports:
          http:
            port: 80
            targetPort: 7880
          rtc-tcp:
            port: 7881
          metrics:
            port: 6789

      jwt:
        controller: jwt
        ports:
          http:
            port: 80
            targetPort: 8080

    serviceMonitor:
      app:
        serviceName: app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    route:
      app:
        hostnames: [ "{{ .Release.Name }}.${SECRET_DOMAIN}" ]
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: *app
                port: 80
          - matches:
              - path:
                  type: PathPrefix
                  value: /sfu
            backendRefs:
              - name: livekit-jwt
                port: 80

    persistence:
      keys:
        type: secret
        name: livekit-keys
        defaultMode: 0600
        globalMounts:
          - path: /config/keys.yaml
            subPath: keys.yaml
