---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/stunner.l7mp.io/udproute_v1.json
apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: livekit
spec:
  parentRefs:
    - name: stunner
      namespace: network
      sectionName: udp
  rules:
    - backendRefs:
        - name: livekit
