---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: conduit-registration-secret
    namespace: matrix
spec:
    encryptedData:
        token: AgBM9p486/g6Utx+s+O8EZgghP5Dh1YAhgQWiWvq6/hGca+xgd0qlOQbgrAMIM7sYsyXXNLXyRGgWMOPV5PejFnhlPEe01FxTj/hwH37Eh9cF34q7jQXEi8YiTp1dc+vWXSB6XMZS9jbhFBVUPNBgoYxy4jDvOCHUKC027DjbMuN7Pis2m0wGl1Bso/j3a6lA3HRM/y8d7DjYAQFe+8sxlyIx7IUalrdqct17kfyPfzTD6FaOK2TAmG/xXvHwYd3E36McMJ2F+DakAR3cWfS8d6SfuKxF0goKbEuHdqlqNkd/LUKArypdaVfLIEqwxkRc1kwblcXakA+DfhipLkMufwtuHVJVFpnabAoMSf+YCU/xczp13mAENf3JBfwx5nnDvjnPc2znLHXw+eSJUVc4GpI0FC1CC2KPjXzftEUh9ybZq0rE3kK+pmdDXCFKDmFBvhj8p/ZIqtlHb+1DxX9BWrItbLRJiiOoqwXGaUqAJteCW+cRgAMKhEdQM4m6Q0FZAmpsynAryJGwrjDoSMqFXqJCdhIfd1D80M2MMh2sXAt31UAIscCxdEHaMWfKWpYJkU1G9+8ZA5mQrEVdwNSMD8cz1/DZULP5NKi2nAwSmkcEVV/NZMTNg45c7FH7KmVXP7UUI4qS7l45co2HnzW9F+YooQSGWGwqtOVcrNs1+BAUmlXBPnw/lFZEWeHHuswA329hpk9GKBUw3q7cj2YeyRR5MMskHDg6UndjYoZ6q5AJ+ZFr+yzEy6E2wNykxNfC2l7J8NLYbF2+m6uxYuY9fL2EgIUlWSe3zU=
