id: heisenbridge
url: http://heisenbridge.matrix.svc
as_token: { { .as_token } }
hs_token: { { .hs_token } }
rate_limited: false
sender_localpart: heisenbridge
namespaces:
    users:
        - regex: "@irc_.*"
          exclusive: true
        - regex: "@heisenbridge:.*"
          exclusive: true
    aliases: []
    rooms: []
heisenbridge:
    media_url: https://matrix.${SECRET_DOMAIN}
