---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
spec:
  components: []
  interval: 1h
  path: ./kubernetes/apps/observability/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app grafana-instance
spec:
  dependsOn:
    - name: grafana-operator
    - name: openebs
      namespace: openebs-system
  components:
    - ../../../../components/oidc
    - ../../../../components/gatus/guarded
  interval: 1h
  path: ./kubernetes/apps/observability/grafana/instance
  postBuild:
    substitute:
      APP: grafana
      NAMESPACE: &namespace observability
      OIDC_DISPLAY_NAME: Grafana
      OIDC_CALLBACK: /login/generic_oauth
      OIDC_GROUP: admins
      OIDC_CLAIM_MAPS: |
        {
          "grafana_role": {
            "joinType": "array",
            "valuesByGroup": {
              "admins@idm.m00nlit.dev": ["GrafanaAdmin"]
            }
          }
        }
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-dashboards
spec:
  components: []
  interval: 1h
  path: ./kubernetes/apps/observability/grafana/dashboards
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: true
  force: true
  patches:
    - patch: |
        - op: add
          path: /spec/instanceSelector
          value:
            matchLabels:
              grafana.internal/instance: grafana
      target:
        kind: GrafanaDashboard
