---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name ${APP}-tls
spec:
  secretName: *name
  issuerRef:
    name: ${ISSUER:=letsencrypt-production-shortlived}
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  duration: 160h
  usages: ["digital signature"]
  dnsNames:
    - "${DOMAIN:=${TLS_SUBDOMAIN:=${SUBDOMAIN:=${APP}}}.${SECRET_DOMAIN}}"
