# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: lidarr-secret
  metadata:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: homepage
stringData:
  api_key: ENC[AES256_GCM,data:rbzkO6RVqVSv+3LObpvgp1SoJiIpBsWxYmYlcb+5wTs=,iv:uaGNcp6RGMdQPIIZhlmB/4aNo1Mn7gWR2ATY6zWGYKs=,tag:DfgaPHzURS8m5pE0TxSwqQ==,type:str]
sops:
  age:
    - recipient: age1689ww93cs2fkv3np57388eyepd789kk3zu47vyx67u8sc48vlprq9qafje
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeGp1SFFLL0sxNDUyVTZu
        b25aVzcyZkhvRlZlalBMUnBxL0JRdlFsemxBCmRlNlhZeVVPQlBGT2h1ODBBVUo2
        SFU0ZGl0TkZrTWxCMjNCQ1RHcjBRRW8KLS0tIEd2d01lUzhHYjB2VGJMSGZvRGJz
        dFN1WTBaUnpGNmVkWE5Cd2w2MkJNUEEKW3Q1HZPjzvy0XTRx9dQGXbZ4Hh/Uwb5g
        E/ji6Rqgc8diu/LTfjvJV2mcuvVQYq1fiibx8G4SaTtb8ngROSXKiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T23:11:27Z"
  mac: ENC[AES256_GCM,data:PnAmIs2OuaCm1nua/sNY/TCUjjjKiT1+rf9LhrPs0UsdfS1v1NFslQYKXNIb5rjfvC1tbnzwRD/McQg4sKRHGHFsuab+NDFFthYNzuONNmhIM1kU3WVVp7C9vTbRPzWFKcCDCnWEDN8xoZsUXVA23z3KvXviix5rjuT5Is4Fghc=,iv:9aSl8Yzz56wOke1E4IIOnVclyTsjAHkD3R4/0kGZixI=,tag:1m6uEu1+w499DXJXn0GZKg==,type:str]
  pgp:
    - created_at: "2025-06-22T23:50:49Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hF4DC0EwVK2S0BUSAQdADCKNPgyDqATq7NWB27t0yW/NjTPgLZ4EoDytfVt2MxIw
        B8enMkoeQzd1szUZDlWUXeWVlwym+DERtWGFm0UaGDANrI7vmzOt5SepIIztaJD0
        0l4BXOxLcVqdWDCBiDw3vE9FSdx8jgNzrIUucBYQCP9b12G3rgnYfoJq6IxDrh+S
        PdFvm6AgjCZ05GWuSWZ7pgZ09aoB13X002J+DlYuUJxbACgv+NbE9ITeiS9WrDFa
        =HrGc
        -----END PGP MESSAGE-----
      fp: F846C93BF4BEAB99D98D29B2DF3CEC6BF015D41D
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
