---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: migadu-${APP}
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app ${APP}
  interval: 1h
  path: ./kubernetes/components/mail/base/migadu
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: ${NAMESPACE}
      MAILBOX_NAME: ${MAILBOX_NAME:=${NAME:=${APP}}}
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: flux-system
  timeout: 5m
  wait: false
