---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: ${APP}-migadu
spec:
  interval: 12h
  approvePlan: auto
  cloud:
    hostname: app.terraform.io
    organization: m00n
    workspaces:
      name: migadu-${APP}
  path: ./terraform/migadu
  vars:
    - name: app
      value: ${APP}
    - name: name
      value: ${MAILBOX_NAME:=${NAME:=${APP}}}
  varsFrom:
    - kind: Secret
      name: cluster-secrets
      varsKeys:
        - SECRET_DOMAIN:domain
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  writeOutputsToSecret:
    name: ${APP}-migadu
  runnerPodTemplate:
    spec:
      envFrom:
      - secretRef:
          name: migadu-token-${APP}