---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/storage.k8s.io/storageclass_v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-vault
allowVolumeExpansion: true
parameters:
  compression: "zstd"
  dedup: "on"
  fstype: "zfs"
  poolname: "vault/storage"
  shared: "yes"
provisioner: zfs.csi.openebs.io
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/storage.k8s.io/storageclass_v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-rpool
allowVolumeExpansion: true
parameters:
  compression: "zstd"
  dedup: "on"
  fstype: "zfs"
  poolname: "rpool/storage"
  shared: "yes"
provisioner: zfs.csi.openebs.io
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/storage.k8s.io/storageclass_v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: zfs-spark
allowVolumeExpansion: true
parameters:
  compression: "zstd"
  dedup: "on"
  fstype: "zfs"
  poolname: "spark"
  shared: "yes"
provisioner: zfs.csi.openebs.io
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/storage.k8s.io/storageclass_v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-spark-block
allowVolumeExpansion: true
parameters:
  compression: "zstd"
  volblocksize: "16K"
  poolname: "spark"
provisioner: zfs.csi.openebs.io
