---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kube-apiserver-route
spec:
  parentRefs:
    - name: internal
      namespace: network
      sectionName: https
  hostnames:
    - "k8s.${SECRET_DOMAIN}"
  rules:
    - backendRefs:
        - name: kubernetes
          namespace: default
          port: 443
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/gateway.networking.k8s.io/backendtlspolicy_v1alpha3.json
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: kube-api-upstream-tls
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: kubernetes
  validation:
    hostname: kubernetes.default.svc
    caCertificateRefs:
      - group: v1
        kind: ConfigMap
        name: kube-root-ca.crt
